apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip_viewer_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: button-app
  template:
    metadata:
      labels:
        app: button-app
    spec:
      containers:
        - name: button-app
          image: dipakrasal2009/ip_viewer:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ip_app_service
spec:
  type: NodePort
  selector:
    app: button-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30036  # You can change this if needed

