apiVersion: v1
kind: Pod
metadata:
  name: master
spec:
  containers:
    - name: master
      image: dipakrasal2009/ansible-base
      ports:
        - containerPort: 22
      securityContext:
        privileged: true

