apiVersion: v1
kind: Pod
metadata:
  name: node2
spec:
  containers:
    - name: master
      image: dipakrasal2009/ansible-ready-image
      ports:
        - containerPort: 22
      securityContext:
        privileged: true

